food/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    #path('admin/', admin.site.urls),
    path('items/',include("items.urls"))
]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

items/urls.py
from django.urls import path
from.import views

app_name = "items"

urlpatterns = [
    path('home/',views.home, name='Home'),
    path('create/', views.create, name='create'),
    path('data/', views.data, name='data'),
    path('recipe_list/', views.recipe_list, name='recipe_list'),
    path('<int:recipe_id>/details/', views.details, name='details'),
    path('<int:recipe_id>/update/', views.update, name='update'),
    path('<int:recipe_id>/delete/', views.delete, name='delete'),

         ]

items/models.py
from django.db import models

class Recipes(models.Model):
    name = models.CharField(max_length=25)
    ingredients = models.TextField(max_length=200)
    process = models.TextField()
    #image = models.ImageField(upload_to='images/',null=True)
    def __str__(self):
        return self.name

items/views.py
from django.shortcuts import render
from django.urls import reverse
from django.http import HttpResponse,HttpResponseRedirect
from .models import Recipes


def home(request):
    return render(request, 'items/home.html')


#1Creating
def create(request):
    return render(request, 'items/create.html')


''' Url path(create) will request to create views logic
    and this create views will request create.html to add recipes'''


#2 Posting to database
def data(request):
    if request.method == "POST":
        Recipes.objects.create(
            name=request.POST["name"],
            ingredients = request.POST["ingredients"],
            process=request.POST["process"],
            #image=request.FILES["image"]
        )
        return HttpResponseRedirect('/items/recipe_list/')
    return render (request, 'items/create.html')


''' After creating recipes in create.html it will requests post the data to data which will be stored in 
    Recipes data base(ORM) and redirects to recipelist(list.html) '''

#3 Fetching Database


def recipe_list(request):
    recipe=Recipes.objects.all()
    return render(request, 'items/list.html', {'recipe': recipe})


''' In this recipe list we can get all data of recipes that are stored in Recipes database'''

#4 Details of recipe


def details(request, recipe_id):
    recipe = Recipes.objects.get(id=recipe_id)
    return render(request, 'items/details.html', {'recipe':recipe})


''' By clicking on recipe name in recipelist(list.html) we can get details of recipe like name, ingredients etc..'''

#5 Update recipe


def update(request, recipe_id):
    
    if request.method == 'GET':
        up= Recipes.objects.get(id=recipe_id)
        return render(request, 'items/update.html', {'up': up})

    else:
        recipe = Recipes.objects.get(id=recipe_id)
        recipe.name = request.POST['name']
        recipe.ingredients = request.POST['ingredients']
        recipe.process = request.POST['process']
        recipe.save()
        r = Recipes.objects.get(id=recipe_id)
        print(r.id)
        return HttpResponseRedirect(reverse('items:recipe_list'))
      

''' update recipe details like name or ingredients, process by geting data and post to database '''

#6 Delete recipe


def delete(request, recipe_id):
    recipe = Recipes.objects.get(id=recipe_id)
    recipe.delete()
    return HttpResponseRedirect(reverse('items:recipe_list'))

items/templates/items/create.html
<a href="/items/home"><h2>Home</h2></a>

<form action="/items/data/" method="post" enctype="multipart/form-data">

    {% csrf_token %}
    name: <input type="text" name="name" placeholder="recipe name"><br>
    ingredients : <input type="text" name="ingredients" placeholder="ingredients"><br>
    process : <input type="text" name="process" placeholder="enter the process"><br>

    <input type="submit" value="Submit"> &nbsp;
    <br>
   &nbsp; <br><a href="/items/recipe_list"> BACK </a>
</form>

items/templates/items/delete.html
<a href="/items/recipe_list"> BACK </a> &nbsp;

items/templates/items/details.html
<a href="/items/home/"><h2>Home</h2></a>

name          : {{recipe.name}}<br>
ingredients   : {{recipe.ingredients}}<br>
process       : {{recipe.process}}<br>
<!img src="{{recipes.image.url}}" height="100px" width="50px"><br>
<br>

<a href="/items/{{recipe.id}}/update/">Update</a> &nbsp;

<a href="/items/{{recipe.id}}/delete/">Delete</a> &nbsp;
<br><br>
<a href="/items/recipe_list"> BACK </a> &nbsp;

items/templates/items/home.html
<h1 class="title">Recipe Project</h1>
<br>
<a href="/items/recipe_list/"><h3>Recipes</h3></a><br>
<a href="/items/create/"><h3>Create Recipe</h3></a> 
<style>
h1{color:green}
</style>

items/templates/items/list.html
<a href="/items/home/"><h2>Home</h2></a>

{% if recipe %}
    {% for item in recipe %}
        <a href="/items/{{item.id}}/details/"> {{item.name}}</a> &nbsp; 
    {% endfor %}
{% else %}
<p>No data created</p>
{% endif %}
<br>
<br><a href="/items/create/"><h3>Add Recipe</h3></a>

items/templates/items/update.html
<a href="/items/home/"><h2>Home</h2></a>



<form action='{% url 'items:update' up.id %}' method="post" enctype="multipart/form-data">

    {% csrf_token %}
    name: <input type="text" name="name" value="{{up.name}}"><br>
    ingredients : <input type="text" name="ingredients" value="{{up.ingredients}}"><br>
    process : <input type="text" name="process" value="{{up.process}}"><br>
    <input type="submit" value="Submit"><br></br>
    <a href="/items/recipe_list"> BACK </a>

</form>